<a href="https://colab.research.google.com/github/Alenushka2013/ML_for_people_tasks/blob/main/HW_2_1_Matrices_and_Vectors_(Introduction_to_Linear_Algebra).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

vector = np.random.uniform(0, 1, 10)
matrix = np.array([[11, 14, 17], [20, 23, 26],  [29, 32, 35]])

print(f'vector = {vector}')
print(f'Розмірність вектора {vector.shape}\n')

print(f'matrix = {matrix}')
print(f'Розмірність матриці {matrix.shape}')

vector = [0.24099676 0.87163219 0.83163454 0.05459202 0.58060477 0.22973533
 0.32475273 0.79815388 0.45308839 0.79281994]
Розмірність вектора (10,)

matrix = [[11 14 17]
 [20 23 26]
 [29 32 35]]
Розмірність матриці (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [2]:
print(f'vector * 2 = {(vector * 2).round(2)}\n')
print(f'matrix * 2 = {matrix * 2}\n')
vector_square = vector ** 2
print(f'Квадрат вектора = {vector_square}')

vector * 2 = [0.48 1.74 1.66 0.11 1.16 0.46 0.65 1.6  0.91 1.59]

matrix * 2 = [[22 28 34]
 [40 46 52]
 [58 64 70]]

Квадрат вектора = [0.05807944 0.75974268 0.691616   0.00298029 0.3371019  0.05277832
 0.10546434 0.63704961 0.20528909 0.62856345]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [3]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [4]:
result_matrix = np.dot(B, A)
print(f'B * A = result_matrix = {result_matrix}\n')
print(f'result_matrix *  C = {np.dot(result_matrix, C)}\n')
print(f'result_matrix * D = {np.dot(result_matrix, D)}')

B * A = result_matrix = [[0.7281 0.5202]
 [0.2034 0.2846]]

result_matrix *  C = [[0.5202]
 [0.2846]]

result_matrix * D = [[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [5]:
#1
result_matrix_transpose = result_matrix.T
print(f'транспонована result_matrix {result_matrix_transpose}')

транспонована result_matrix [[0.7281 0.2034]
 [0.5202 0.2846]]


In [6]:
#2
vector_transpose = vector.T
print(f'вектор {vector}\n')
print(f'\"транспонований\" вектор {vector_transpose}\n')
print('Змін немає' if np.array_equal(vector, vector_transpose) else 'Зміни є')

вектор [0.24099676 0.87163219 0.83163454 0.05459202 0.58060477 0.22973533
 0.32475273 0.79815388 0.45308839 0.79281994]

"транспонований" вектор [0.24099676 0.87163219 0.83163454 0.05459202 0.58060477 0.22973533
 0.32475273 0.79815388 0.45308839 0.79281994]

Змін немає


In [7]:
#3
column_vector = np.expand_dims(vector, axis=1)
print(f'вектор {vector}\n')
print(f'вектор - стовпець {column_vector}\n')
print('Змін немає' if np.array_equal(vector, column_vector) else 'Зміни є')

вектор [0.24099676 0.87163219 0.83163454 0.05459202 0.58060477 0.22973533
 0.32475273 0.79815388 0.45308839 0.79281994]

вектор - стовпець [[0.24099676]
 [0.87163219]
 [0.83163454]
 [0.05459202]
 [0.58060477]
 [0.22973533]
 [0.32475273]
 [0.79815388]
 [0.45308839]
 [0.79281994]]

Зміни є


In [8]:
# 4
column_vector_transpose = column_vector.T
print(f'транспонований вектор-стовбець {column_vector_transpose} \nмає розмірність {column_vector_transpose.shape}')

транспонований вектор-стовбець [[0.24099676 0.87163219 0.83163454 0.05459202 0.58060477 0.22973533
  0.32475273 0.79815388 0.45308839 0.79281994]] 
має розмірність (1, 10)


In [9]:
print(f'Початковий вектор {vector} \nмає розмірність {vector.shape}\n')
print(f'вектор - стовпець {column_vector} \nмає розмірність {column_vector.shape}\n')
print(f'транспонований вектор-стовбець {column_vector_transpose} \nмає розмірність {column_vector_transpose.shape}\n')
print('Змін немає' if np.array_equal(vector, column_vector_transpose) else 'Зміни є')

Початковий вектор [0.24099676 0.87163219 0.83163454 0.05459202 0.58060477 0.22973533
 0.32475273 0.79815388 0.45308839 0.79281994] 
має розмірність (10,)

вектор - стовпець [[0.24099676]
 [0.87163219]
 [0.83163454]
 [0.05459202]
 [0.58060477]
 [0.22973533]
 [0.32475273]
 [0.79815388]
 [0.45308839]
 [0.79281994]] 
має розмірність (10, 1)

транспонований вектор-стовбець [[0.24099676 0.87163219 0.83163454 0.05459202 0.58060477 0.22973533
  0.32475273 0.79815388 0.45308839 0.79281994]] 
має розмірність (1, 10)

Зміни є


Операцію транспонування *array_name.T* некоректно використовувати для масивів що мають один вимір, як vector з розмірністю (10,). В таких випадках можна скористатися *np.expand_dims(array_name, axis=1)*.

Тут вже потрібно бути уважним до появи ще одного виміру: транспонування вектора-стовбця *vector_column.T* повертає масив розмірністю (1, 10), який схожий на початковий вектор, та через різні розмірності вони не рівні.

Подвійна оперція транспонування до двовимірної матриці повертає ту ж саму матрицю.