<a href="https://colab.research.google.com/github/Alenushka2013/ML_for_people_tasks/blob/main/Python_HW7_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [1]:
import numpy as np

In [2]:
arr = np.array([5, 15, 25, 35, 45])
arr_zeros = np.zeros(7)
arr_ones = np.ones(6)
arr_num = np.arange(10, 20)

In [3]:
arr

array([ 5, 15, 25, 35, 45])

In [4]:
arr_zeros

array([0., 0., 0., 0., 0., 0., 0.])

In [5]:
arr_ones

array([1., 1., 1., 1., 1., 1.])

In [6]:
arr_num

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])


---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [7]:
numbers = np.array([12, 24, 36, 48, 60])
print(numbers * 2)
print(numbers + 10)
print(numbers ** 2)
print(numbers ** 0.5)

[ 24  48  72  96 120]
[22 34 46 58 70]
[ 144  576 1296 2304 3600]
[3.46410162 4.89897949 6.         6.92820323 7.74596669]



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [8]:
data = [18, 27, 33, 41, 52, 68, 79]
print(f'Середнє значення {np.mean(data)}')
print(f'Мінімум {np.min(data)}')
print(f'Максимум {np.max(data)}')
print(f'Сумa всіх елементів {np.sum(data)}')

Середнє значення 45.42857142857143
Мінімум 18
Максимум 79
Сумa всіх елементів 318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [9]:
arr = np.array([15, 22, 35, 44, 58, 67])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[arr > 40])

15
67
[22 35 44]
[44 58 67]



---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [10]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [11]:
matrix.shape

(3, 3)

In [12]:
matrix[0, :]

array([2, 4, 6])

In [13]:
matrix[:, 1]

array([ 4, 10, 16])

In [14]:
print(np.sum(matrix))

90


In [15]:
print(np.mean(matrix))

10.0
